name: Docker

on:
  push:
    tags: 
      - depends*

jobs:
  build_base:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
      - name: build_base
        run: bash server-docker/shell/build_image/build_base2004_image.sh
      
      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/mmo-server-base
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID

          docker tag mmo-server-base:20.04 $IMAGE_ID:20.04
          docker tag mmo-server-base:20.04 $IMAGE_ID:latest
          docker push $IMAGE_ID

  build_depends:
    needs: build_base
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
      - name: pull_base
        run: |
          docker pull docker.pkg.github.com/${{ github.repository }}/mmo-server-base:20.04
          docker tag docker.pkg.github.com/${{ github.repository }}/mmo-server-base:20.04 mmo-server-base:20.04

      - name: build_depends
        run: bash server-docker/shell/build_image/build_mmo-server-depends.sh

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/mmo-server-depends
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID

          docker tag mmo-server-depends:base $IMAGE_ID:base
          docker tag mmo-server-depends:latest $IMAGE_ID:latest
          docker push $IMAGE_ID

 